### ISSUE TITLE
<oneentry> disappeared if parse SMCAT to SCXML in 6.0.4

### ISSUE THREAD

**Issue by AnKlim** [sverweij/state-machine-cat#114]
Hello,
currently I am using your project to for converting SMCAT to SCXML format. I try to convert

`^fraud?: transaction fraudulent?;

initial -> reserved;
reserved -> quoted:
    quote
    requested;
quoted -> ^fraud?: payment;
^fraud? -> ticketed: [no];
^fraud? -> removed: [yes];
ticketed -> final;
removed -> final;`
into SCXML.

In version 6.0.3 I've got current SCXML:
![image](https://user-images.githubusercontent.com/35483429/76425776-27716b00-63bb-11ea-8e48-44a1d5d3c890.png)
But in version 6.0.4 I've got next result:
![image](https://user-images.githubusercontent.com/35483429/76425898-525bbf00-63bb-11ea-8ddf-0795eaefdf5f.png)

As you see tag <onentry> disappeared. Is it correct behavior?

Thanks

**Comment by sverweij** [comment]
Hi @AnKlim thanks for raising this. That indeed is not expected behaviour - unless the _desugar_ switch is on, in which case it _is_ expected (you can read about desugaring [here](https://github.com/sverweij/state-machine-cat/blob/develop/docs/desugar.md#de-sugaring-state-machines)).

Desugar replaces any pseudo states it can with state transitions - in the case of the _choice_ pseudo state it will connect incoming and outgoing transitions see [de-sugaring choice](https://github.com/sverweij/state-machine-cat/blob/develop/docs/desugar.md#de-sugaring-choice)

=> Could you check if indeed the de-sugar option is on?

with the switch _on_:

![image](https://user-images.githubusercontent.com/4822597/76441718-2989f880-63c0-11ea-8aa4-36a94e37151d.png)


with the switch _off_:

![image](https://user-images.githubusercontent.com/4822597/76441611-fba4b400-63bf-11ea-9fdf-ab0b11e6f97d.png)

**Comment by AnKlim** [comment]
@sverweij you were right. Desugar was switched ON. Thanks :)

**Comment by AnKlim** [comment]
Hello @sverweij.
I've add to scxml <onentry> tag with <log> tag inside, but in JSON output in "body" I have nothing. Is it correct parser? That would be a great if it's possible to get all contained inside of <onentry> and <onexit> tag in body as a sting for example. 
![image](https://user-images.githubusercontent.com/35483429/77998116-38b5f380-7339-11ea-8764-c60f9a446d14.png)

**Comment by sverweij** [comment]
Hi @AnKlim thank you for raising this. It seems a different issue from the one you re-opened if I see correctly? (For a next time - you can just open a new issue)

State-machine-cat has been confined to [SCXML core constructs](https://github.com/sverweij/state-machine-cat/blob/develop/docs/SCXML.md#what-is-supported) as these can be meaningfully represented in state transitions diagrams (which is state-machine-cat's primary goal). That said - it treats _executable content_ (like your `<log>` statement)see the [SCXML specs](https://www.w3.org/TR/scxml/#contents) for terms & details) transparently. Which means it should work as you expect already. 

If you run 

```sh
smcat --output-type json --input-type scxml tmp_executable_content.xml -o -
```

it transforms <details>
<summary>this input scxml</summary>

```scxml
<?xml version="1.0" encoding="UTF-8"?>
<scxml xmlns="http://www.w3.org/2005/07/scxml" initial="backlog" version="1.0">
    <state id="backlog">
        <transition event="pull" target="doing"/>
    </state>
    <state id="doing">
        <onentry>
            <log expr="'whoop tee doo!!'"/>
        </onentry>
        <onexit>submit PR</onexit>
        <transition event="functionality_built" target="review"/>
    </state>
    <state id="review">
        <onexit>merge PR to develop</onexit>
        <transition cond="code quality not ok" target="doing"/>
        <transition cond="code quality ok" target="QA"/>
        <transition cond="code has minor issues" target="QA"/>
    </state>
    <state id="QA">
        <transition cond="not acceptable" target="doing"/>
        <transition cond="ok but issue(s) found" target="done"/>
        <transition cond="okie dokie" target="done"/>
    </state>
    <state id="done">
        <transition target="final"/>
    </state>
    <final id="final">
    </final>
</scxml>
```

</details>


into  

<details>
<summary>this json output</summary>

```json
{
    "states": [
        {
            "name": "initial",
            "type": "initial"
        },
        {
            "name": "backlog",
            "type": "regular"
        },
        {
            "name": "doing",
            "type": "regular",
            "actions": [
                {
                    "type": "entry",
                    "body": "<log expr=\"'whoop tee doo!!'\"/>"
                },
                {
                    "type": "exit",
                    "body": "submit PR"
                }
            ]
        },
        {
            "name": "review",
            "type": "regular",
            "actions": [
                {
                    "type": "exit",
                    "body": "merge PR to develop"
                }
            ]
        },
        {
            "name": "QA",
            "type": "regular"
        },
        {
            "name": "done",
            "type": "regular"
        },
        {
            "name": "final",
            "type": "final"
        }
    ],
    "transitions": [
        {
            "from": "initial",
            "to": "backlog"
        },
        {
            "from": "backlog",
            "to": "doing",
            "event": "pull",
            "label": "pull"
        },
        {
            "from": "doing",
            "to": "review",
            "event": "functionality_built",
            "label": "functionality_built"
        },
        {
            "from": "review",
            "to": "doing",
            "cond": "code quality not ok",
            "label": "[code quality not ok]"
        },
        {
            "from": "review",
            "to": "QA",
            "cond": "code quality ok",
            "label": "[code quality ok]"
        },
        {
            "from": "review",
            "to": "QA",
            "cond": "code has minor issues",
            "label": "[code has minor issues]"
        },
        {
            "from": "QA",
            "to": "doing",
            "cond": "not acceptable",
            "label": "[not acceptable]"
        },
        {
            "from": "QA",
            "to": "done",
            "cond": "ok but issue(s) found",
            "label": "[ok but issue(s) found]"
        },
        {
            "from": "QA",
            "to": "done",
            "cond": "okie dokie",
            "label": "[okie dokie]"
        },
        {
            "from": "done",
            "to": "final"
        }
    ]
}
```

</details>

The online interpreter did the same, but it 'disappeared'  because the online interpreter didn't properly escape xml tags. It now does, though, so you should see any _executable content_ like `<log>` and `<if>` statements again as you'd expect it to

> Note: I fixed it _before_ posting this comment, as it was a potential security vulnerability.
