### ISSUE TITLE
Advantages over PlantUML?

### ISSUE THREAD

**Issue by xeruf** [sverweij/state-machine-cat#169]
PlantUML supports quite sophisticated state diagrams, abstracted over GraphViz: https://plantuml.com/state-diagram

I am not quite sure what makes this easier, help me understand :)

Somewhat related to https://github.com/sverweij/state-machine-cat/issues/126

**Comment by sverweij** [comment]
Grüß gott @xeruf - first of: if PlantUML works in your situation by all means use it - it seems to have become a great tool.

In 2016 I wrote state-machine-cat as I couldn't find a text-to-diagram tool for state machines that (1) ran in the browser (2) without a server component (3) supported a large portion of state diagrams UML. This was useful as I needed to make diagrams at customers that didn't allow installation of software (but who did allow internet access). At more permissive customers and at home it helped me embed state charts in documentation and write state charts with my then favorite editor (Atom) and through Node.js I could use it on CI tools as well.

At that time PlantUML (and other text-to-diagram tools) did not fit that bill. As far as I'm aware this situation hasn't changed much since. An exception could be what davidkpiano has been doing with visualizations for xstate ([xstate-viz](https://github.com/statelyai/xstate-viz)), though.
