### ISSUE TITLE
Error while using state-machine-cat in NUXT application

### ISSUE THREAD

**Issue by yugal-compro** [sverweij/state-machine-cat#194]
**Use Case:**
    I would like to use state-machine-cat in a NUXT application

**Code:**
   plugins/state-machine-cat.js
   
```
   import smcat from 'state-machine-cat';

   export default defineNuxtPlugin((nuxtApp) => ({
     provide: {
       smcat
     }
   }));
```
   stateDiagram.vue
   
```
<template>
  <div>
    <h1>This is component of state diagram</h1>
    <div
      id="svg"
      v-html="svg"
    />
    <v-btn @click="showDiagram()">click me</v-btn>
  </div>

</template>

<script>

export default {
  setup() {
    const { $smcat } = useNuxtApp();
    let svg;
    try {
      const lSVGInAString = $smcat.render(
        `
            initial => backlog;
            backlog => doing;
            doing => test;
        `,
        {
          outputType: 'svg'
        }
      );
      // eslint-disable-next-line no-unused-vars
      svg = lSVGInAString;
    } catch (pError) {
      console.error(pError);
    }
    return {
      svg
    };
  }
<script/>
```

**Expected Action:** 
   Show State Machine Diagram without any errors

**Error Faced:**
Giving error inside state-machine-cat directory of node modules. 
**Top-level await is not available in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari14" + 2 overrides)**
![image](https://github.com/sverweij/state-machine-cat/assets/107843548/e4beb255-4d21-489f-ad66-55d237d4c6d8)

**Comment by sverweij** [comment]
hi @yugal-compro thanks for raising this issue. The error message you see is because the environment configured for the nuxt framework cannot handle modern JavaScript - from the screenshot of the error message it seems it doesn't support [dynamic imports](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import) ([since node 13, as well as in pretty ancient versions of most  browsers](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import#browser_compatibility)) and/ or [await](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await) which is supported since [node 7.6, as well as even more ancient browser versions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await#browser_compatibility). 

The specific complaint nuxt has seems to be about top level await which is a more recent development, but not particularly ancient either (see [toplevel await compatibility table](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await#browser_compatibility)).

I'd advise to configure nuxt to more recent minimum versions of browsers and/ or nodejs versions.
