### ISSUE TITLE
note removes line color

### ISSUE THREAD

**Issue by OneCyrus** [sverweij/state-machine-cat#51]
adding a note removes the color from the line:
```
initial,

stopped, paused;
#test
paused  => stopped [color="blue"] : stop;
```

gives:

![image](https://user-images.githubusercontent.com/7747800/58412619-1f884a80-8077-11e9-94e1-a56b818d2868.png)

without note. the line is blue
```
initial,

stopped, paused;
paused  => stopped [color="blue"] : stop;
```
![image](https://user-images.githubusercontent.com/7747800/58412655-2fa02a00-8077-11e9-9bb6-403d7e346f6d.png)

**Comment by sverweij** [comment]
hi @OneCyrus - well spotted, thanks!

I have an inkling of where this is going wrong (in a [non-dry handlebars template](https://github.com/sverweij/state-machine-cat/blob/develop/src/render/dot/dot.template.hbs))- and it should be easy enough to fix. I'll try to do it it the course of this week - I'll tag you in this thread when something is ready.

**Comment by sverweij** [comment]
@OneCyrus - it indeed seemed straightforward to fix - see the bug fix #52 ☝️  

You can check whether it works for you at one of these spots:
- beta site: https://sverweij.gitlab.io/state-machine-cat/ (note: git**lab**) 
- or, if you use the npm package, the fix is in a beta version as well: `state-machine-cat@5.0.3-beta-1`

Let me know if it works for you.

**Comment by OneCyrus** [comment]
perfect. thanks!

**Comment by sverweij** [comment]
5.0.3 is now both on state-machine-cat.js.org and on npm. Thanks for the quick verification!
