### ISSUE TITLE
Broken dependency viz.js – "Invalid asm.js: Function definition doesn't match use"

### ISSUE THREAD

**Issue by slhck** [sverweij/state-machine-cat#82]
### Expected Behavior

I am trying to convert a simple smcat file to SVG:

```
➜ cat test.smcat
initial,
"media player off",

"media player on" {
  stopped, playing, paused;

  stopped => playing : play;
  playing => stopped : stop;
  playing => paused  : pause;
  paused  => playing : play;
  paused  => stopped : stop;
};

initial            => "media player off";
"media player off" => stopped           : power;
"media player on"  => "media player off" : power;
```

I expect `smcat -o test.svg < test.smcat` to create that SVG file.

### Current Behavior

```
➜ smcat -o test.svg < test.smcat
(node:11096) V8: /usr/local/lib/node_modules/state-machine-cat/node_modules/viz.js/viz.js:33 Invalid asm.js: Function definition doesn't match use
```

### Possible Solution

Seems this is related to [this upstream bug](https://github.com/mdaines/viz.js/issues/96) in `viz.js` that was never fixed. Now this project is archived, and it seems there is no obvious solution to the issue. I think it cannot be used as a dependency anymore.

The same error is referenced in [this issue](https://github.com/nrwl/nx/issues/1551#issuecomment-536049262) as well. One solution is proposed: to use [dagre](https://github.com/dagrejs/dagre/) instead.

### Your Environment

* Version used: 5.3.3
* Node version: 12.10.0
* Operating System and version: macOS 10.14.6

**Comment by sverweij** [comment]
you can instead use the native graphviz like so ...

```sh
smcat -T dot -o - | dot -T svg > test.svg
```

(believe me when I say dagre is not an alternative ... :-) )

**Comment by slhck** [comment]
You forgot the input file:

```
smcat -T dot -o - < test.smcat | dot -T svg > test.svg
```

But otherwise it's working fine, thank you! 👍 

(Should the built-in GraphViz support be removed then, or is this issue only affecting certain platforms?)

**Comment by sverweij** [comment]
@slhck dôh! well spotted.

About viz.js: I've been looking for alternatives to viz.js - but found nothing suitable yet
- I've been looking into ELK and sprotty which have nice layout algorithms, but the really difficult part (auto-sizing boxes to text content) is left as _an excercise for the reader_.
- Similar for vis, d3, dagre etc - which all lack one or more features (i.e. clustering nodes for nested machines, sectioning of nodes, auto sizing ...)
- Upgrading to v2 of viz.js might alleviate some of the error messages - but is not a sustainable option either.
- Another option is to take up maintenance of viz.js and/ or make sure GraphViz gets wasm as a supported platform (- which amounts to the same).

Until that I'll probably keep viz.js part of the distro as long as it's safe. Also: the warning is sent to stderr IIRC, so the rendered picture is not affected (let me know if you experience otherwise).

**Comment by slhck** [comment]
Thanks for the summary of alternatives. I personally find it very suboptimal to just archive a project without giving others a chance to maintain it. But I have not a lot of experience with npm or WebAssembly to be of help. Just a confused end user here.

The message gets printed on stderr, so it's not an immediate issue.

However, for the end users it might be better to already let them know in advance that something isn't working, or catch this particular exception and let the user know what's wrong (i.e., it's not `smcat`'s fault). Not sure if this is something that'd help.

**Comment by sverweij** [comment]
@slhck sorry about the info-dump :-) 

On adding a warning message in advance: that's an excellent suggestion. I'll add it in the next release (and likely earlier in the documentation).

**Comment by slhck** [comment]
Sounds great, thanks!

**Comment by slhck** [comment]
Please go away, stalebot. (I would suggest we keep this open since it's actually an open issue?)

**Comment by sverweij** [comment]
I've labeled the issue so stale bot stays silent.
